//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseClass
    {
        public string ClassID { get; set; }
        public string ClassName { get; set; }
        public int Duration { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DOB { get; set; }
    }
}
